version: "3.8"

networks:
  todo-board-network:

services:
  production:
    networks:
      - todo-board-network
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-board
    environment:
      - NODE_ENV=production
      - PORT=3003
      - MONGO_DB_URI=mongodb://mongo:27017/todo_board
    ports:
      - "3003:3003"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: ["yarn", "start"]
    depends_on:
      - mongo

  to-do-board-dev:
    networks:
      - todo-board-network
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-board-dev
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_DB_URI=mongodb://mongo:27017/todo_board
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: ["yarn", "dev"]
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    networks:
      - todo-board-network
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_DB_URI: "mongodb://mongo:27017"

volumes:
  mongo-data:
