import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@todo/components";
import { getInitialStoreData } from "@todo/helper";

import StoreProvider from "./components/provider/provider";
import ErrorBoundary from "@todo/components/error-boundary/error-boundary";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialStoreData = getInitialStoreData();
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider initialStoreData={initialStoreData}>
          <Header />
          <ErrorBoundary>{children}</ErrorBoundary>
        </StoreProvider>
      </body>
    </html>
  );
}
